version: "3.3"

services:
  web:
    build: .
    command: >
      sh -c "alembic upgrade head
             python main.py"
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    env_file:
      - ./source/.env
    depends_on:
      - db

  db:
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rodeo_db


volumes:
#  static_files:
  postgres_data:
