"""added image url in image models

Revision ID: 0aac590b651d
Revises: 5281deac1c0e
Create Date: 2023-06-12 22:07:49.071118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aac590b651d'
down_revision = '5281deac1c0e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('news', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'image_url')
    op.drop_column('images', 'image_url')
    # ### end Alembic commands ###
