"""added tournament_models

Revision ID: 0e937bd788ed
Revises: 475787a2a97c
Create Date: 2023-06-24 14:10:37.085885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e937bd788ed'
down_revision = '475787a2a97c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
