"""added about-us page

Revision ID: 53fb0d59a709
Revises: 9d91015ddf0f
Create Date: 2023-07-31 12:41:09.510100

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_fields
from sqlalchemy_fields.storages import FileSystemStorage


# revision identifiers, used by Alembic.
revision = '53fb0d59a709'
down_revision = '9d91015ddf0f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('about_us',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upper_title', sa.String(), nullable=True),
    sa.Column('preview_image', sqlalchemy_fields.types.image.ImageType(storage=FileSystemStorage), nullable=True),
    sa.Column('preview_image_url', sa.String(), nullable=True),
    sa.Column('appeal', sa.String(), nullable=True),
    sa.Column('founder_image', sqlalchemy_fields.types.image.ImageType(storage=FileSystemStorage), nullable=True),
    sa.Column('founder_image_url', sa.String(), nullable=True),
    sa.Column('regulation', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('about_us')
    # ### end Alembic commands ###
