"""added about-us page

Revision ID: 9d91015ddf0f
Revises: b1e86251cfce
Create Date: 2023-07-31 11:57:06.775762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d91015ddf0f'
down_revision = 'b1e86251cfce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
