"""clear

Revision ID: ab1f96c04cb8
Revises: f62b12830b0e
Create Date: 2023-07-31 13:08:49.064037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab1f96c04cb8'
down_revision = 'f62b12830b0e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
