"""added tournament_models

Revision ID: b19558f4bf27
Revises: 0e937bd788ed
Create Date: 2023-06-24 14:12:37.776980

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_fields
from sqlalchemy_fields.storages import FileSystemStorage

# revision identifiers, used by Alembic.
revision = 'b19558f4bf27'
down_revision = '0e937bd788ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournament_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_en', sa.String(), nullable=True),
    sa.Column('title_ru', sa.String(), nullable=True),
    sa.Column('title_kg', sa.String(), nullable=True),
    sa.Column('description_en', sa.String(), nullable=True),
    sa.Column('description_ru', sa.String(), nullable=True),
    sa.Column('description_kg', sa.String(), nullable=True),
    sa.Column('image', sqlalchemy_fields.types.image.ImageType(storage=FileSystemStorage), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tournament_title',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sqlalchemy_fields.types.image.ImageType(storage=FileSystemStorage), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('title_en', sa.String(), nullable=True),
    sa.Column('title_ru', sa.String(), nullable=True),
    sa.Column('title_kg', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tournaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sqlalchemy_fields.types.image.ImageType(storage=FileSystemStorage), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('tournament_title_en', sa.String(), nullable=True),
    sa.Column('tournament_title_ru', sa.String(), nullable=True),
    sa.Column('tournament_title_kg', sa.String(), nullable=True),
    sa.Column('location_en', sa.String(), nullable=True),
    sa.Column('location_ru', sa.String(), nullable=True),
    sa.Column('location_kg', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('time', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tournaments')
    op.drop_table('tournament_title')
    op.drop_table('tournament_events')
    # ### end Alembic commands ###
