"""added new model

Revision ID: b1e86251cfce
Revises: eb6be183946b
Create Date: 2023-07-09 20:47:52.407156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1e86251cfce'
down_revision = 'eb6be183946b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aplications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_owner_name', sa.String(), nullable=True),
    sa.Column('amount_of_participants', sa.Integer(), nullable=True),
    sa.Column('participants_names', sa.String(), nullable=True),
    sa.Column('participants_ages', sa.String(), nullable=True),
    sa.Column('phone_numbers', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aplications')
    # ### end Alembic commands ###
