"""added  chammp models

Revision ID: eb6be183946b
Revises: 252203321f17
Create Date: 2023-06-24 15:26:03.417921

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_fields
from sqlalchemy_fields.storages import FileSystemStorage

# revision identifiers, used by Alembic.
revision = 'eb6be183946b'
down_revision = '252203321f17'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sqlalchemy_fields.types.image.ImageType(storage=FileSystemStorage), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('champions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.Column('first_place_id', sa.Integer(), nullable=True),
    sa.Column('second_place_id', sa.Integer(), nullable=True),
    sa.Column('third_place_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['first_place_id'], ['participants.id'], ),
    sa.ForeignKeyConstraint(['second_place_id'], ['participants.id'], ),
    sa.ForeignKeyConstraint(['third_place_id'], ['participants.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('champions')
    op.drop_table('participants')
    # ### end Alembic commands ###
