"""changed about us column

Revision ID: f62b12830b0e
Revises: 53fb0d59a709
Create Date: 2023-07-31 12:59:31.614322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f62b12830b0e'
down_revision = '53fb0d59a709'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('about_us', sa.Column('title_en', sa.String(), nullable=True))
    op.add_column('about_us', sa.Column('title_ru', sa.String(), nullable=True))
    op.add_column('about_us', sa.Column('title_kg', sa.String(), nullable=True))
    op.add_column('about_us', sa.Column('appeal_en', sa.String(), nullable=True))
    op.add_column('about_us', sa.Column('appeal_ru', sa.String(), nullable=True))
    op.add_column('about_us', sa.Column('appeal_kg', sa.String(), nullable=True))
    op.add_column('about_us', sa.Column('founder_info_en', sa.String(), nullable=True))
    op.add_column('about_us', sa.Column('founder_info_ru', sa.String(), nullable=True))
    op.add_column('about_us', sa.Column('founder_info_kg', sa.String(), nullable=True))
    op.add_column('about_us', sa.Column('regulation_en', sa.String(), nullable=True))
    op.add_column('about_us', sa.Column('regulation_ru', sa.String(), nullable=True))
    op.add_column('about_us', sa.Column('regulation_kg', sa.String(), nullable=True))
    op.drop_column('about_us', 'regulation')
    op.drop_column('about_us', 'upper_title')
    op.drop_column('about_us', 'appeal')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('about_us', sa.Column('appeal', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('about_us', sa.Column('upper_title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('about_us', sa.Column('regulation', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('about_us', 'regulation_kg')
    op.drop_column('about_us', 'regulation_ru')
    op.drop_column('about_us', 'regulation_en')
    op.drop_column('about_us', 'founder_info_kg')
    op.drop_column('about_us', 'founder_info_ru')
    op.drop_column('about_us', 'founder_info_en')
    op.drop_column('about_us', 'appeal_kg')
    op.drop_column('about_us', 'appeal_ru')
    op.drop_column('about_us', 'appeal_en')
    op.drop_column('about_us', 'title_kg')
    op.drop_column('about_us', 'title_ru')
    op.drop_column('about_us', 'title_en')
    # ### end Alembic commands ###
